client_id = "335c38b504f9036243ec71c1aa34cad0"
name = "New DiscountRay"
handle = "local-discountray-13"
application_url = "https://dev.efoli.com/sate/salahuddin/repo/socket"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_themes,write_checkouts,write_discounts,write_products"

[auth]
redirect_urls = [ "https://dev.efoli.com/sate/salahuddin/repo/socket/"]

[webhooks]
api_version = "2024-07"

[app_proxy]
url = "https://dev.efoli.com/sate/salahuddin/repo/socket/"
subpath = "local-discountray-13"
prefix = "apps"

[pos]
embedded = false
